-- JET Loadout
FG.terroristLoadout = {
	{'autoshotgun', 1, 7},
	{'shotgunshell', 12, 7},
	{'shotgunshell', 12, 7},
	{'handcannon', 1, 8},
	{'handcannonround', 6, 8},
	{'shotgunshell', 12, 9},
	{'handcannonround', 12, 10},
	{'crowbar', 1, 11},
	{'antibleeding2', 2, 12},--Plastiseal
	{'midazolam', 2, 13},
	{'opium', 1, 14},
	{'oxygentank', 1, 15},
	{'flashlight', 1, 16},
	{'batterycell', 1, 16},
	{'jetmask', 1, 2},
	{'pirateclothes', 1, 3},
	{'piratebodyarmor', 1, 4},
	{'autoinjectorheadset', 1, 1},
	{'combatstimulantsyringe', 1, 1},
	{'idcardjet', 1, 0},
}

-- MERCS Ladout
FG.nexpharmaLoadout = {
	{'assaultrifle', 1, 7},
	{'assaultriflemagazine', 1, 7},
	{'revolver', 1, 8},
	{'revolverround', 6, 8},
	{'revolverround', 12, 11},
	{'assaultriflemagazine', 2, 9},
	{'assaultriflemagazine', 2, 10},
	{'divingknife', 1, 12},
	{'antibleeding2', 2, 13},--Plastiseal
	{'midazolam', 2, 14},
	{'opium', 1, 15},
	{'flashlight', 1, 16},
	{'batterycell', 1, 16},
	{'piratebandana', 1, 2},
	{'securityuniform2', 1, 3},
	{'nexsuit', 1, 4},
	{'combatstimulantsyringe', 1, 4},
	{'oxygentank', 1, 4},
	{'headset', 1, 1},
	{'idcardmercs', 1, 0}
}

FG.loadedFiles['loadoutTables'] = true